version: '3'

services: 
    postgres:
        image: 'postgres:latest'
    # default port 5432, username/db = postgres and password postgres_password

    redis:
        image: 'redis:latest'
    # port is by default 6379

    nginx:
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - '3050:80'
        depends_on: 
            - api
            - client
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on: 
            - postgres
            - redis
    
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./client:/app
    
    worker:
        build: 
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on: 
            - redis
